import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
  #    "~/.config/alacritty/themes/themes/night_owl.toml"
]

[env]
TERM = "alacritty-direct"

[cursor.style]
shape = "Beam"
[font]
size=11
[font.bold]
family = "HackNerdFont"
style = "Bold"
[font.italic]
family = "HackNerdFont"
style = "Italic"
[font.normal]
family = "HackNerdFont"
style = "Regular"
[window]
opacity = 0.92
blur = true
[shell]
program = "/usr/bin/zsh"

[scrolling]
# Scrollback buffer and scroll sensitivity
history = 10000
multiplier = 3



[[keyboard.bindings]]
key = "Return"
mods = "Super|Shift"
action = "SpawnNewInstance"



